### ISSUE TITLE
[Exception] v1.6.0的exe程序运行桌宠闪退

### ISSUE THREAD

**Issue by line486** [isHarryh/Ark-Pets#22]
通过ArkPets_Setup-v1.6.0.exe安装的程序，可以进入主页面，选择模型和修改设置，但无法启动，启动后会闪退。
v1.6版本的jar包可以正常运行。
![image](https://user-images.githubusercontent.com/97444410/212872570-a943355b-4755-4925-bbe0-d6ff17ceeced.png)
![image](https://user-images.githubusercontent.com/97444410/212872831-2cdc6147-1bc1-4da0-9fe2-7d3733e8c007.png)
![image](https://user-images.githubusercontent.com/97444410/212872905-dc58a60d-eaf5-47b6-aeed-63bb9b5ba045.png)

**Comment by isHarryh** [comment]
收到，我们正在排查问题。

**Comment by isHarryh** [comment]
Stacktrace 如下：
```
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: no awt in java.library.path
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:172)
	at com.isharryh.arkpets.EmbeddedLauncher.main(EmbeddedLauncher.java:38)
	at com.isharryh.arkpets.DesktopLauncher.main(DesktopLauncher.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
Caused by: java.lang.UnsatisfiedLinkError: no awt in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at java.awt.Toolkit$3.run(Unknown Source)
	at java.awt.Toolkit$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Unknown Source)
	at java.awt.Toolkit.<clinit>(Unknown Source)
	at java.awt.SystemTray.addNotify(Unknown Source)
	at java.awt.SystemTray.<init>(Unknown Source)
	at java.awt.SystemTray.initializeSystemTrayIfNeeded(Unknown Source)
	at java.awt.SystemTray.getSystemTray(Unknown Source)
	at com.isharryh.arkpets.ArkTray.<init>(ArkTray.java:39)
	at com.isharryh.arkpets.ArkPets.create(ArkPets.java:104)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	... 8 more
```
原因是未将`awt.dll`加入JRE中导致托盘功能未正常展开，属于本人疏忽。

**Comment by isHarryh** [comment]
将相关依赖（awt, fontmanager, t2k）加入JRE后已重新打包exe，请您验证是否解决。

**Comment by line486** [comment]
问题已解决，感谢您的关注。
