### ISSUE TITLE
[Exception] 解压模型完成后立即抛出异常

### ISSUE THREAD

**Issue by zhangxichang** [isHarryh/Ark-Pets#26]
版本`2.0.0`，异常提示：
```
[Exception] AccessDeniedException
[Message] temp\models_unzipped\Ark-Models-main\models -> models

[StackTrace]
Caused by java.nio.file.AccessDeniedException: temp\models_unzipped\Ark-Models-main\models -> models
  at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
  at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
  at java.base/sun.nio.fs.WindowsFileCopy.move(Unknown Source)
  at java.base/sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
  at java.base/java.nio.file.Files.move(Unknown Source)
  at cn.harryh.arkpets.controllers.Homepage$6$1.preVisitDirectory(Homepage.java:1008)
  at cn.harryh.arkpets.controllers.Homepage$6$1.preVisitDirectory(Homepage.java:993)
  at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
  at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
  at cn.harryh.arkpets.controllers.Homepage$6.call(Homepage.java:993)
  at cn.harryh.arkpets.controllers.Homepage$6.call(Homepage.java:983)
  at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by zhangxichang** [comment]
有没有手动下载模型的方式？

**Comment by isHarryh** [comment]
遇到的问题是：在模型解压后从临时文件夹移动解压后的文件到程序目录时拒绝访问。  
可能是偶发性故障，常见原因如：文件系统问题；防病毒软件或其他程序占用；解压文件损坏等。  
建议：重新尝试。若问题仍然存在，请发送完整日志文件。

**Comment by isHarryh** [comment]
> 有没有手动下载模型的方式？

可以前往 https://github.com/isHarryh/Ark-Models 中下载该仓库的压缩包，解压其中的 **文件夹和models_data.json** 到程序目录。然后在启动器中点击“重载”

**Comment by isHarryh** [comment]
调查表明，使用部分反病毒软件（例如卡巴斯基）时，此类软件会频繁扫描文件，导致文件占用或拒绝访问。关闭反病毒软件，然后重试即可。
