### ISSUE TITLE
[Exception] 无法启动桌宠窗口: GdxRuntimeException

### ISSUE THREAD

**Issue by isHarryh** [isHarryh/Ark-Pets#30]
版本`2.0.1`，在个别设备上启动桌宠时，启动器总是提示“检测到桌宠异常退出”，core.log 日志内容如下：
```
# *** ArkPets Log - core (PID5600) ***
# Created: 2023-05-07 16:41:36,173
# OS: Windows 10 (amd64)
# Java version: 20.0.1
# Working directory: C:\ArkPets

16:41:36,210 [INFO] System: Entering the app of EmbeddedLauncher
16:41:36,912 [ERROR] System: An fatal error occurs in the runtime of Lwjgl3Application, details see below.
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
	at cn.harryh.arkpets.EmbeddedLauncher.main(EmbeddedLauncher.java:70)
```
可见是 libGDX 无法创建窗口（GdxRuntimeException: Couldn't create window）导致的，抛出异常的位置：  
https://github.com/libgdx/libgdx/blob/1.11.0/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java#L527

**Comment by isHarryh** [comment]
鉴于此问题属于 libGDX/LWJGL 的问题，已在  libgdx/libgdx#7139 提出 Issue。

**Comment by isHarryh** [comment]
无其他可供调查的线索，并且此问题在这一年间未有再次复现，因此关闭此议题。
