### ISSUE TITLE
[Exception] 无法启动桌宠窗口: java.awt.AWTError

### ISSUE THREAD

**Issue by NoMathExpectation** [isHarryh/Ark-Pets#36]
版本`v2.1.0`。每次试图启动桌宠总是会产生这个错误，无法启动。

日志：[core.13956.log](https://github.com/isHarryh/Ark-Pets/files/11857857/core.13956.log)

```
# *** ArkPets Log - core (PID13956) ***
# Created: 2023-06-25 01:55:25,286
# OS: Windows 11 (amd64)
# Java version: 17.0.7
# Working directory: E:\ArkPets

01:55:25,818 [INFO] System: Entering the app of EmbeddedLauncher
01:55:29,045 [INFO] App: Create
01:55:29,050 [INFO] App: Using model asset "models\301_cutter\build_char_301_cutter"
01:55:29,545 [INFO] Character: Canvas size 149 * 168
01:55:29,626 [INFO] App: Using behavior class "BehaviorOperBuild"
01:55:30,687 [ERROR] System: An fatal error occurs in the runtime of Lwjgl3Application, details see below.
com.badlogic.gdx.utils.GdxRuntimeException: java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:172)
	at cn.harryh.arkpets.EmbeddedLauncher.main(EmbeddedLauncher.java:87)
Caused by: java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
	at java.desktop/java.awt.Toolkit.newAWTError(Unknown Source)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
	at java.desktop/java.awt.SystemTray.addNotify(Unknown Source)
	at java.desktop/java.awt.SystemTray.<init>(Unknown Source)
	at java.desktop/java.awt.SystemTray.initializeSystemTrayIfNeeded(Unknown Source)
	at java.desktop/java.awt.SystemTray.getSystemTray(Unknown Source)
	at cn.harryh.arkpets.ArkTray.<init>(ArkTray.java:41)
	at cn.harryh.arkpets.ArkPets.create(ArkPets.java:103)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	... 23 more
```

**Comment by isHarryh** [comment]
这看起来是和 JRE 有关的问题。请问你是否在本地曾经安装过 Java？如果有，请尝试卸载 Java 后再运行桌宠，以便排查环境问题。

**Comment by NoMathExpectation** [comment]
我装了好几个 java ，是用来工作的，不可能全卸了啊...
不过估计是java运行时指定错误的问题，请问有没有什么办法指定运行时呢

**Comment by isHarryh** [comment]
情况已经了解了，确实是由桌宠没有正确选择到运行时所致。本地安装了 Java 的情况下似乎会对exe安装包所带的运行时有干扰，我们后续会研究修复方法。

当前exe版本不支持强制指定运行时，你可以尝试删除 Java 相关的环境变量再运行exe，或考虑使用jar版本的命令行运行。

**Comment by isHarryh** [comment]
由于此议题长期搁置，现将其关闭。

另外，当前 ArkPets 已发展至 v3.x 版本，你可尝试问题是否已经在当前版本得到解决。
