### ISSUE TITLE
[Exception] 桌宠运行时异常退出 

### ISSUE THREAD

**Issue by Sophon7680** [isHarryh/Ark-Pets#38]
```
[Exception] UnexpectedExitCodeException
[Message] The process exited with a non-zero exit code: 1

[StackTrace]
Caused by cn.harryh.arkpets.utils.JavaProcess.UnexpectedExitCodeException: The process exited with a non-zero exit code: 1
  at cn.harryh.arkpets.ArkHomeFX$1.call(ArkHomeFX.java:121)
  at cn.harryh.arkpets.ArkHomeFX$1.call(ArkHomeFX.java:94)
  at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by isHarryh** [comment]
请说明软件版本，并提供`core.log`日志。

**Comment by isHarryh** [comment]
（坐等日志）目前涉及崩溃的已知问题是 #30 ，推测你的问题也可能是这个问题。

![-457ea6d462a926e9.jpg](https://github.com/isHarryh/Ark-Pets/assets/107977864/4ef5e917-f811-458d-8b42-62e6cc7dcc9f)
