### ISSUE TITLE
[Exception] 无法启动桌宠窗口

### ISSUE THREAD

**Issue by 114514xian** [isHarryh/Ark-Pets#44]
我使用的JAVA版本为JAVA20，报错信息如下：
```
[Exception] UnexpectedExitCodeException
[Message] The process exited with a non-zero exit code: -1

[StackTrace]
Caused by cn.harryh.arkpets.utils.JavaProcess.UnexpectedExitCodeException: The process exited with a non-zero exit code: -1
  at cn.harryh.arkpets.ArkHomeFX$1.call(ArkHomeFX.java:118)
  at cn.harryh.arkpets.ArkHomeFX$1.call(ArkHomeFX.java:91)
  at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```
![捕获](https://github.com/isHarryh/Ark-Pets/assets/111653580/53c5ce4a-f4b7-4ff1-acc0-8ecd8def753a)
请问我该如何解决此问题（

**Comment by isHarryh** [comment]
请进入 选项-浏览日志，把任意一个`core.log`的内容贴到这里。

**Comment by isHarryh** [comment]
（坐等日志）目前涉及崩溃的已知问题是 #30 和 #36 ，推测你的问题也可能是这些问题中的一个。

![-457ea6d462a926e9.jpg](https://github.com/isHarryh/Ark-Pets/assets/107977864/4ef5e917-f811-458d-8b42-62e6cc7dcc9f)
